# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7cc31c67-ef3f-485b-a614-b3ad0c8786bf'
  imageRepository: 'wonderingkahojuiceshop'
  containerRegistry: 'nginxplusingress.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'nginxplusingress2091b936-auth'
  azureSubscription: 'LHK - Azure PoC -Network(0531dae3-35f1-4131-87df-71f0455cf088)'
  acr.name: nginxplusingress
  acr.repo.name: helm/juice-shop
  HELM_EXPERIMENTAL_OCI: 1
  namespaces: 'demo'
  agentPath: '/azp/_work/1/juice-shop/'


  # Agent VM image name
  vmImageName: 'Default'

jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      name: $(vmImageName)
    environment: 'Wonderingkahojuiceshop-7563.$(namespaces)'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Kubernetes@1
              displayName: Login to Kubernetes
              inputs:
                connectionType: 'Azure Resource Manager'
                azureSubscriptionEndpoint: $(azureSubscription)
                azureResourceGroup: 'ACW'
                useClusterAdmin: true
                kubernetesCluster: 'nginx-plus-ingress'
                command: login

            - task: AzureCLI@2
              displayName: Update Project
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  cd /azp/_work/1/juice-shop
                  git pull
                  apt-get install unzip

#            - task: HelmInstaller@1
#              inputs:
#                helmVersionToInstall: '3.9.4'

            - task: HelmDeploy@0
              displayName: Helm Deploy
              inputs:
                # Azure Container Registry
                azureSubscriptionEndpointForACR: $(azureSubscription)
                azureResourceGroupForACR: "ACW"
                azureContainerRegistry: "nginxplusingress"
                connectionType: 'Azure Resource Manager'
                azureSubscription: $(azureSubscription)
                useClusterAdmin: true
                azureResourceGroup: 'ACW'
                kubernetesCluster: 'nginx-plus-ingress'
                namespace: $(namespaces)
                command: install
                chartType: 'FilePath'
                chartPath: '$(agentPath)/chart/juice-shop-3.14.3.tgz'
                releaseName: 'juice-shop'

            - task: KubernetesManifest@0
              displayName: KubernetesManifest
              inputs:
                action: deploy
                namespace: $(namespaces)
                manifests: |
                  $(agentPath)/manifests/juice-shop-dashboard-secret.yaml
                  $(agentPath)/manifests/virtual-server.yaml
                  $(agentPath)/manifests/waf.yaml
                  $(agentPath)/manifests/ap-dataguard-alarm-policy.yaml
                  $(agentPath)/manifests/ap-apple-uds.yaml
                  $(agentPath)/manifests/syslog.yaml
                  $(agentPath)/manifests/ap-logconf.yaml

#            - task: KubernetesManifest@0
#              displayName: Delete
#              inputs:
#                action: delete
#                arguments: deployment syslog
#                namespace: $(namespaces)
#
#            - task: KubernetesManifest@0
#              displayName: Delete
#              inputs:
#                action: delete
#                arguments: service syslog-svc
#                namespace: $(namespaces)




