apiVersion : apps/v1
kind: Deployment
metadata:
  name: wonderingkahojuiceshop 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wonderingkahojuiceshop
  template:
    metadata:
      labels:
        app: wonderingkahojuiceshop 
    spec:
      containers:
        - name: wonderingkahojuiceshop 
          image: nginxplusingress.azurecr.io/wonderingkahojuiceshop
          ports:
          - containerPort: 80