apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "dataguard-alarm"
    securityLogs:
    - enable: true
      apLogConf: "logconf"
      logDest: "syslog:server=syslog-svc.demo:514"
